### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by vitormhenrique** [clashman/it8951_arduino#2]
Hello, 

Do you have an example on how to put a streaming from the esp32 to the e-ink display?

Thanks!

**Comment by clashman** [comment]
More info please ;)

**Comment by vitormhenrique** [comment]
My bad! Fat fingered an enter! With no comment!

**Comment by clashman** [comment]
I have it laying around on my local drive somewhere. But it is really easy to accomplish. Although the ESP has not enough RAM, the IT8951 has. You can use HttpClient or something similar and just transfer the buffer in chunks to the IT8951.

**Comment by clashman** [comment]
I renamed the repository to fix this issue.
