### ISSUE TITLE
A thank you, not an issue

### ISSUE THREAD

**Issue by stan69b** [clashman/it8951_arduino#4]
Just wanted to thank you for this piece of code. I've been striggling to make my 10.3 inch display work on esp32 without any luck, spent countless hours and ended using one of my raspberry pi zero just to make sur the screen was working. then off in a drawer .... but then what do you know, I ended up on this page, executed the ino and BOOM, it just worked ! 

If i manage, I plan on adding a wifi post api to be abble to push images to the esp32 and want to add your python converter to home assistant so that the centralized home system can push new images to render. all this with the esp32 deep sleep ability :) So thank you again for your hard work :D 

if you are intrested in the code i plan to make, leave a little comment here and i'll post it on github :) 

have a nice day.

**Comment by stan69b** [comment]
here is a link to my fork :) 
It adds wifi support and websocket payload rendering. By rendering line by line an image sent with multiple websocket payloads.
more info here for anyone interested : 
https://github.com/stan69b/Waveshare-10.3-it8951-esp32

Thanks again for this lib, it literally made my project possible :)

**Comment by clashman** [comment]
Thanks for your messages. You're welcome :)
