### ISSUE TITLE
convert_image.py not working

### ISSUE THREAD

**Issue by mmarcelofrm** [clashman/it8951_arduino#5]
First of all, thank you so much for the port, is really useful.

I'm having issues with the image converter,  I think that another script is missing here, because subprocess is calling trying to call convert, but, there is no that file in the repo.

subprocess.call(['convert', '-size', '1x16', 'gradient:gray100-gray0', colortable_path])

Could you help me with this part, please?

**Comment by clashman** [comment]
It is calling imagemagick. Install that and you will be fine.
