### ISSUE TITLE
[Question] Streaming to IT8951

### ISSUE THREAD

**Issue by vititu** [clashman/it8951_arduino#6]
First I would like to thank you for this.

After countless hours of trying and searching around I was finally able to show something on my 9.7 inches e-ink display.

I'm actually trying to fetch an endpoint that returns a bmp image on full resolution and display it on the screen. I guess ESP32 does not have enough memory to handle that. I saw you mentioning that it's possible to send it to the IT8951.

Do you have any pointers on how to do that? Any sample code? Any hint is appreciated.

**Comment by clashman** [comment]
Call IT8951_Load_Begin and LCDWaitForReady. Then call bcm2835_spi_transfer for every few pixels that you fetched from your endpoint.

Anyways, nowadays the easiest way is just to just get an ESP that has additional RAM.
